# Generated by Django 5.1.5 on 2025-02-04 16:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school_class", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        help_text="Age must be between 12 and 25.",
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(25),
                        ],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Optional phone number.",
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(help_text="Home address of the student.")),
                (
                    "enrollment_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date when student was enrolled."
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        help_text="The class this student is enrolled in.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="school_class.class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "permissions": [
                    ("can_view_student", "Can view student"),
                    ("can_edit_student", "Can edit student"),
                ],
            },
        ),
    ]
