# Generated by Django 5.1.5 on 2025-02-04 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects the student is studying.",
                related_name="students",
                to="subjects.subject",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                help_text="The user associated with this student.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["user"], name="students_st_user_id_e808e6_idx"),
        ),
    ]
