# Generated by Django 5.1.5 on 2025-02-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(
                help_text="First name of the student.", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(
                help_text="Last name of the student.", max_length=50, null=True
            ),
        ),
    ]
