# Generated by Django 5.1.5 on 2025-02-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_first_name_student_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
    ]
