# Generated by Django 5.1.5 on 2025-02-04 16:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        help_text="Age must be between 22 and 65.",
                        validators=[
                            django.core.validators.MinValueValidator(22),
                            django.core.validators.MaxValueValidator(65),
                        ],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Optional phone number.",
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(help_text="Home address of the teacher.")),
                (
                    "joining_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date when teacher joined."
                    ),
                ),
                (
                    "subject",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Subjects the teacher is teaching.",
                        related_name="teachers",
                        to="subjects.subject",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user associated with this teacher.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "permissions": [
                    ("can_view_teacher", "Can view teacher"),
                    ("can_edit_teacher", "Can edit teacher"),
                ],
                "indexes": [
                    models.Index(fields=["user"], name="teachers_te_user_id_d97704_idx")
                ],
            },
        ),
    ]
