# Generated by Django 5.1.5 on 2025-02-04 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school_class", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "permissions": [
                    ("can_view_subject", "Can view subject"),
                    ("can_edit_subject", "Can edit subject"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClassTeacherSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_teacher_subjects",
                        to="school_class.class",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_assign_subject", "Can assign subject to class teacher")
                ],
            },
        ),
    ]
