# Generated by Django 5.1.5 on 2025-02-04 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classteachersubject",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_class_subjects",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="classteachersubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_class_subjects",
                to="subjects.subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="classteachersubject",
            constraint=models.UniqueConstraint(
                fields=("class_obj", "teacher", "subject"),
                name="unique_class_teacher_subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classteachersubject",
            unique_together={("class_obj", "teacher", "subject")},
        ),
    ]
