# Generated by Django 5.1.5 on 2025-02-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Present", "Present"), ("Absent", "Absent")],
                        max_length=10,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "permissions": [
                    ("can_mark_attendance", "Can mark attendance"),
                    ("can_view_attendance", "Can view attendance"),
                    ("can_edit_attendance", "Can edit attendance"),
                ],
            },
        ),
    ]
